<a href="https://colab.research.google.com/github/LAMECH9/LAMECH9/blob/main/NAIVE_BAYES.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report
import os

In [ ]:
#TRY LOADING DATASET FROM CSV
csv_file= '/content/naive_bayes_data.csv'
if os.path.exists(csv_file):
    df=pd.read_csv(csv_file)
else:
     raise FileNotFoundError("Dataset not found.Please ulpoad naive_bayes_data.csv")

In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   feature1     100 non-null    object 
 1   feature2     100 non-null    float64
 2   class_label  100 non-null    int64  
dtypes: float64(1), int64(1), object(1)
memory usage: 2.5+ KB
None


In [ ]:
print(df.describe())

         feature2  class_label
count  100.000000       100.00
mean    52.982272         0.55
std     25.959256         0.50
min     10.496991         0.00
25%     31.517272         0.00
50%     54.246176         1.00
75%     75.624123         1.00
max     98.708541         1.00


In [ ]:
df.head()

feature1   feature2  class_label
0        C  27.884411            0
1        A  10.496991            1
2        C  83.391529            0
3        C  73.617161            0
4        A  75.610645            0

In [ ]:
#Convert categorical feature to numeric
if df['feature1'].dtype == 'object':
    df['feature1']=df['feature1'].astype('category').cat.codes

In [ ]:
#Define features and target variable
X=df[['feature1','feature2']].values
Y=df['class_label'].values

In [ ]:
X

array([[ 2.        , 27.88441134],
       [ 0.        , 10.49699054],
       [ 2.        , 83.39152856],
       [ 2.        , 73.61716095],
       [ 0.        , 75.61064512],
       [ 0.        , 79.4143312 ],
       [ 2.        , 16.66401866],
       [ 1.        , 42.26191557],
       [ 2.        , 20.42821536],
       [ 2.        , 87.67930833],
       [ 2.        , 66.09683141],
       [ 2.        , 39.78082224],
       [ 0.        , 15.72025153],
       [ 2.        , 37.98840895],
       [ 1.        , 39.26649898],
       [ 0.        , 75.66455605],
       [ 1.        , 67.38017242],
       [ 1.        , 89.84914683],
       [ 1.        , 52.49934326],
       [ 1.        , 20.76348213],
       [ 0.        , 74.19203085],
       [ 0.        , 78.47065438],
       [ 1.        , 60.51494778],
       [ 1.        , 79.3870462 ],
       [ 0.        , 54.44160367],
       [ 0.        , 57.04595464],
       [ 0.        , 48.47869165],
       [ 2.        , 12.28772141],
       [ 2.        ,

In [ ]:
Y

array([0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1])

In [ ]:
#Split into training and test sets
X_train,X_test,Y_train,Y_test=train_test_split(X,Y, test_size=0.2,random_state=42)

In [ ]:
#Create and train the Naive Bayes model
model= GaussianNB()
model.fit(X_train,Y_train)

GaussianNB()

In [ ]:
#Predict
y_pred=model.predict(X_test)

In [ ]:
y_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1])

In [ ]:
# Evaluate model
accuracy=accuracy_score(Y_test,y_pred)
report=classification_report(Y_test,y_pred)

print(f"Accuracy:{accuracy}")
print("Classification Report:\n",report)


Accuracy:0.45
Classification Report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00         9
           1       0.50      0.82      0.62        11

    accuracy                           0.45        20
   macro avg       0.25      0.41      0.31        20
weighted avg       0.28      0.45      0.34        20



In [ ]:
#Function to predict class labe for new data
def predict_class(feature1_value, feature2_value):
    #Convert categorical value to numeric if needed
    if isinstance(feature1_value, str):
        feature1_value=pd.Series([feature1_value]).astype('category').cat.codes[0]
    prediction=model.predict(np.array([[feature1_value,feature2_value]]))
    print(f"Predicted class label: {prediction[0]}")
    return prediction[0]

In [ ]:
#Example prediction
predict_class('A', 50)  #Change values as needed

Predicted class label: 1


np.int64(1)